import React from "react";
import "./Terms.css"; // Make sure to adjust the path if necessary

import Footer from "../components/Footer";

const Terms = () => {
  return (
    

    <div className="terms-container">
        
      <h1>BlueGen Terms of Service</h1>
      <p><em>Last modified: October 19th, 2024</em></p>

      <h2>Introduction</h2>
      <p>
        Welcome to BlueGen, your AI-powered Bhagavad Gita companion. By accessing and using the BlueGen website (the "Website"), you agree to abide by these Terms of Service (the "Terms"). If you do not agree to these Terms, please do not use the Website.
      </p>

      <h2>Use of the Website</h2>
      <p>
        BlueGen is designed for both personal and educational use. Users can engage with our AI chatbot powered by GitaGPT for spiritual guidance and explore the Book Section and Quotes Section for deeper insights into the Bhagavad Gita. The content provided is for informational purposes only, and users may utilize the teachings shared by the Website for personal reflection and growth.
      </p>

      <h2>Intellectual Property</h2>
      <p>
        All content, including but not limited to text, images, graphics, and software, is the property of BlueGen and is protected by applicable copyright and intellectual property laws. Users are free to use the insights and responses generated by the AI chatbot for personal purposes; however, any reproduction or distribution of the content must credit BlueGen.
      </p>

      <h2>User Conduct</h2>
      <p>
        You agree not to misuse the Website or engage in any unlawful conduct. This includes, but is not limited to, attempting to disrupt the service, bypassing security measures, or using the Website for harmful purposes.
      </p>

      <h2>Disclaimer of Warranties</h2>
      <p>
        The Website is provided "as is" without any warranties, either express or implied. BlueGen makes no representations regarding the reliability, accuracy, or completeness of the content provided through the Website.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        BlueGen shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the Website. This includes, but is not limited to, any errors in content or any loss or damage resulting from the use of information obtained through the Website.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless BlueGen, its affiliates, and their respective officers, directors, employees, and agents from any claims or demands arising out of your use of the Website, your violation of these Terms, or any violation of the rights of another.
      </p>

      <h2>Changes to These Terms</h2>
      <p>
        BlueGen reserves the right to modify these Terms at any time. Your continued use of the Website after any changes constitutes your acceptance of the modified Terms.
      </p>

      <h2>Termination</h2>
      <p>
        BlueGen may terminate or suspend your access to the Website at any time, without prior notice, for any reason, including but not limited to violations of these Terms or any applicable law.
      </p>

      <h2>Governing Law</h2>
      <p>
        These Terms and any disputes arising from them shall be governed by the laws of the jurisdiction in which BlueGen operates. Any legal actions related to these Terms shall be brought in the courts of that jurisdiction.
      </p>

      <h2>BlueGen 2024. All rights reserved.</h2>
      <Footer />
    </div>
  );
};

export default Terms;
